# pyproject.toml

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "benderslib"
version = "0.0.1"
description = "An Extensible Benders Decomposition Library in Python"
readme = "README.md"
license = { text = "GPL-3.0" }
authors = [
    { name = "Peng-Hui Guo", email = "m@guo.ph" },
]

dependencies = [
    #    "numpy>=1.20",
    #    "pandas",
]

[project.urls]
Homepage = "https://benders.dev"
Repository = "https://github.com/phguo/benderslib"