# coding:utf-8

from .core import BendersParams, MasterProblem, SubProblem, SubProblems, BendersSolver
from .cut import ClassicalOCGen, ClassicalFCGen, CombinatorialFCGen, CombinatorialOCGen, LShapedOCGen, LShapedFCGen


class ClassicalBenders(BendersSolver):
    """
    A built-in implementation of the classical Benders decomposition method.
    It builds a Benders decomposition framework using the provided master problem,
    subproblem, and complicating variables.
    The optimality cut is defined by :class:`ClassicalOC` and generated by :class:`ClassicalOCGen`;
    the feasibility cut is defined by :class:`ClassicalFC` and generated by :class:`ClassicalFCGen`.

    .. caution::
        The class :class:`ClassicalBenders` requires the **subproblem be pure LP**.

    Parameters
    ----------
    master_problem : MasterProblem
        An instance of :class:`MasterProblem` representing the master problem.
    sub_problem : SubProblem
        An instance of :class:`SubProblem` representing the subproblem.
    complicating_vars : list[str]
        A list of names of the complicating variables in the master problem.
    params : BendersParams, optional
        An instance of :class:`BendersParams` containing parameters for the Benders decomposition process.
        If not provided, default parameters will be used.
    """

    def __init__(
            self,
            master_problem: MasterProblem,
            sub_problem: SubProblem,
            complicating_vars: list[str],
            optimality_cut=ClassicalOCGen,
            feasibility_cut=ClassicalFCGen,
            params: BendersParams = BendersParams()
    ):
        super().__init__(
            master_problem,
            sub_problem,
            complicating_vars,
            optimality_cut,
            feasibility_cut,
            params
        )


class CombinatorialBenders(BendersSolver):
    """
    A built-in implementation of the Combinatorial Benders Decomposition method.
    It builds a Benders decomposition framework using the provided master problem,
    subproblem, and complicating variables.
    The optimality cut is defined by :class:`CombinatorialOC` and generated by :class:`CombinatorialOCGen`;
    the feasibility cut is defined by :class:`NoGoodCut` and generated by :class:`CombinatorialFCGen`.

    .. caution::
        The class :class:`CombinatorialBenders` requires the **complicating variables be pure binary (0-1)**.

    Parameters
    ----------
    master_problem : MasterProblem
        An instance of :class:`MasterProblem` representing the master problem.
    sub_problem : SubProblem
        An instance of :class:`SubProblem` representing the subproblem.
    complicating_vars : list[str]
        A list of names of the complicating variables in the master problem.
    params : BendersParams, optional
        An instance of :class:`BendersParams` containing parameters for the Benders decomposition process.
        If not provided, default parameters will be used.
    """

    def __init__(
            self,
            master_problem: MasterProblem,
            sub_problem: SubProblem,
            complicating_vars: list,
            optimality_cut=CombinatorialOCGen,
            feasibility_cut=CombinatorialFCGen,
            params: BendersParams = BendersParams()
    ):
        super().__init__(
            master_problem,
            sub_problem,
            complicating_vars,
            optimality_cut,
            feasibility_cut,
            params
        )


class LShaped(BendersSolver):

    def __init__(
            self,
            master_problem: MasterProblem,
            sub_problem: SubProblems | SubProblem,
            complicating_vars: list,
            estimators: list = None,
            optimality_cut=LShapedOCGen,
            feasibility_cut=LShapedFCGen,
            # Parameters
            multi_opti_cut: bool = False,
            multi_feas_cut: bool = False,
            params: BendersParams = BendersParams()
    ):
        # Setup master and subproblems
        master_problem.complicating_vars = complicating_vars
        for sub in sub_problem:
            sub.complicating_vars = complicating_vars
        sub_problem.estimators = estimators
        sub_problem.multi_opti_cut = multi_opti_cut
        sub_problem.multi_feas_cut = multi_feas_cut

        super().__init__(
            master_problem,
            sub_problem,
            complicating_vars,
            optimality_cut,
            feasibility_cut,
            params
        )


class IntegerLShaped(BendersSolver):
    pass


class AnnotatedLShaped(BendersSolver):
    pass


class GeneralizedBenders(BendersSolver):
    pass


class LogicBasedBenders(BendersSolver):
    pass


class BendersDual(BendersSolver):
    pass


if __name__ == '__main__':
    pass
