# coding:utf-8
import inspect
from typing import Callable, Type

from .core import BendersParams, MasterProblem, SubProblem, SubProblems, BendersSolver, LogicBasedSubProblem, \
    CutGenerator, _FuncWrapperSub
from .cut import ClassicalOCGen, ClassicalFCGen, CombinatorialFCGen, CombinatorialOCGen, LShapedOCGen, LShapedFCGen, \
    IntegerLShapedOCGen, IntegerLShapedFCGen, GeneralizedOCGen, GeneralizedFCGen


class ClassicalBenders(BendersSolver):
    """An implementation of :doc:`../tutorials/classical`.

    It builds a Benders decomposition framework using the provided master problem,
    subproblem, and complicating variables.
    The optimality cut is defined by :class:`ClassicalOC` and generated by :class:`ClassicalOCGen`;
    the feasibility cut is defined by :class:`ClassicalFC` and generated by :class:`ClassicalFCGen`.

    .. caution::
        The class :class:`ClassicalBenders` requires the **subproblem be pure LP**.

    Parameters
    ----------

    master_problem : MasterProblem
        An instance of :class:`MasterProblem` representing the master problem.
    sub_problem : SubProblem
        An instance of :class:`SubProblem` representing the subproblem.
    complicating_vars : list[str]
        A list of names of the complicating variables.
    params : BendersParams, optional
        An instance of :class:`BendersParams` containing parameters for the Benders decomposition process.
        If not provided, default parameters will be used.

    Example
    ----------

    .. code-block:: python

        from benderslib import ClassicalBenders, MasterProblem, SubProblem, Gurobi

        # Define master and subproblem models
        master_model = ...  # Define your master problem model here
        sub_model = ...     # Define your subproblem model here

        # Initialize master and subproblem
        mp = MasterProblem(Gurobi(master_model))
        sp = SubProblem(Gurobi(sub_model))

        # Define complicating variables
        complicating_vars = ['x1', 'x2', 'x3']

        # Initialize and solve
        BD = ClassicalBenders(mp, sp, complicating_vars)
        BD.solve()
    """

    def __init__(
            self,
            master_problem: MasterProblem,
            sub_problem: SubProblem,
            complicating_vars: list[str],
            optimality_cut=ClassicalOCGen,
            feasibility_cut=ClassicalFCGen,
            params: BendersParams = BendersParams()
    ):
        super().__init__(
            master_problem,
            sub_problem,
            complicating_vars,
            optimality_cut,
            feasibility_cut,
            params
        )

    @classmethod
    def from_models(
            cls,
            master_model,
            master_solver,
            sub_model,
            sub_solver,
            complicating_vars,
            optimality_cut=ClassicalOCGen,
            feasibility_cut=ClassicalFCGen,
            prob=None,
            params: BendersParams = BendersParams()
    ):
        return super().from_models(
            master_model,
            master_solver,
            sub_model,
            sub_solver,
            complicating_vars,
            optimality_cut,
            feasibility_cut,
            prob,
            params
        )


class CombinatorialBenders(BendersSolver):
    """An implementation of :doc:`../tutorials/cbd`.

    It builds a Benders decomposition framework using the provided master problem,
    subproblem, and complicating variables.
    The optimality cut is defined by :class:`CombinatorialOC` and generated by :class:`CombinatorialOCGen`;
    the feasibility cut is defined by :class:`NoGoodFC` and generated by :class:`CombinatorialFCGen`.

    .. caution::
        The class :class:`CombinatorialBenders` requires the **complicating variables be pure binary (0-1)**.

    Parameters
    ----------

    master_problem : MasterProblem
        An instance of :class:`MasterProblem` representing the master problem.
    sub_problem : SubProblem
        An instance of :class:`SubProblem` representing the subproblem.
    complicating_vars : list[str]
        A list of names of the complicating variables.
    params : BendersParams, optional
        An instance of :class:`BendersParams` containing parameters for the Benders decomposition process.
        If not provided, default parameters will be used.

    Example
    ----------

    .. code-block:: python

        from benderslib import CombinatorialBenders, MasterProblem, SubProblem, Gurobi

        # Define master and subproblem models
        master_model = ...  # Define your master problem model here
        sub_model = ...     # Define your subproblem model here

        # Initialize master and subproblem
        mp = MasterProblem(Gurobi(master_model))
        sp = SubProblem(Gurobi(sub_model))

        # Define complicating variables (must be binary)
        complicating_vars = ['x1', 'x2', 'x3']

        # Initialize and solve
        BD = CombinatorialBenders(mp, sp, complicating_vars)
        BD.solve()
    """

    def __init__(
            self,
            master_problem: MasterProblem,
            sub_problem: SubProblem,
            complicating_vars: list[str],
            optimality_cut=CombinatorialOCGen,
            feasibility_cut=CombinatorialFCGen,
            params: BendersParams = BendersParams()
    ):
        super().__init__(
            master_problem,
            sub_problem,
            complicating_vars,
            optimality_cut,
            feasibility_cut,
            params
        )

    @classmethod
    def from_models(
            cls,
            master_model,
            master_solver,
            sub_model,
            sub_solver,
            complicating_vars,
            optimality_cut=CombinatorialOCGen,
            feasibility_cut=CombinatorialFCGen,
            prob=None,
            params: BendersParams = BendersParams()
    ):
        return super().from_models(
            master_model,
            master_solver,
            sub_model,
            sub_solver,
            complicating_vars,
            optimality_cut,
            feasibility_cut,
            prob,
            params
        )


class LShaped(BendersSolver):
    """An implementation of :doc:`../tutorials/lshape`.

    It builds a Benders decomposition framework using the provided master problem,
    subproblem, and complicating variables.
    The optimality cut is defined by :class:`LShapedOC` (single-cut) or :class:`ClassicalOC` (multi-cut),
    and generated by :class:`LShapedOCGen`;
    the feasibility cut is defined by :class:`ClassicalFC` and generated by :class:`LShapedFCGen`.

    Note that L-shaped method is a generalization of classical Benders
    decomposition applied to two-stage stochastic programming problems.
    Therefore, :class:`ClassicalOC` and :class:`ClassicalFC` are also used in the L-shaped method.

    .. caution::
        The class :class:`LShaped` requires the (second-stage) **subproblems be pure LP**.

    Parameters
    ----------

    master_problem : MasterProblem
        An instance of :class:`MasterProblem` representing the master problem.
    sub_problem : SubProblems
        An instance of :class:`SubProblems` representing the collection of subproblems.
    complicating_vars : list[str]
        A list of names of the complicating variables.
    params : BendersParams, optional
        An instance of :class:`BendersParams` containing parameters for the Benders decomposition process.
        If not provided, default parameters will be used.

    Example
    ----------

    .. code-block:: python

        from benderslib import LShaped, MasterProblem, SubProblems, Gurobi

        # Define master and subproblem models
        master_model = ...  # Define your master problem model here
        sub_models = [...]  # Define your list of subproblem models here
        probs = [1/len(sub_models)] * len(sub_models)  # Define probabilities for each scenario

        # Initialize master and subproblems
        mp = MasterProblem(Gurobi(master_model))
        sp = SubProblems([Gurobi(sm) for sm in sub_models], probs=probs)

        # Define complicating variables
        complicating_vars = ['x1', 'x2', 'x3']

        # Initialize and solve
        BD = LShaped(mp, sp, complicating_vars)
        BD.solve()
    """

    def __init__(
            self,
            master_problem: MasterProblem,
            sub_problem: SubProblems,
            complicating_vars: list[str],
            optimality_cut=LShapedOCGen,
            feasibility_cut=LShapedFCGen,
            params: BendersParams = BendersParams()
    ):
        super().__init__(
            master_problem,
            sub_problem,
            complicating_vars,
            optimality_cut,
            feasibility_cut,
            params
        )

    @classmethod
    def from_models(
            cls,
            master_model,
            master_solver,
            sub_model,
            sub_solver,
            complicating_vars,
            optimality_cut=LShapedOCGen,
            feasibility_cut=LShapedFCGen,
            prob=None,
            params: BendersParams = BendersParams()
    ):
        return super().from_models(
            master_model,
            master_solver,
            sub_model,
            sub_solver,
            complicating_vars,
            optimality_cut,
            feasibility_cut,
            prob,
            params
        )


class IntegerLShaped(BendersSolver):
    """An implementation of :doc:`../tutorials/ilshape`.

    It is for two-stage stochastic programming with binary complicating variables and integer recourse.
    It builds a Benders decomposition framework using the provided master problem,
    subproblem, and complicating variables.
    The optimality cut is defined by :class:`CombinatorialOC` and generated by :class:`IntegerLShapedOCGen`;
    the feasibility cut is defined by :class:`NoGoodFC` and generated by :class:`IntegerLShapedFCGen`.

    The integer L-shaped method is an extension of the L-shaped method and the Combinatorial Benders decomposition
    to solve two-stage stochastic integer programming problems.
    The cut used in this method are the same as those in Combinatorial Benders decomposition,
    and the algorithmic framework is similar to that of the L-shaped method.

    .. caution::
        The class :class:`IntegerLShaped` requires the complicating variables to be **pure binary (0-1)**,
        integer variables in the subproblems are allowed.

    Parameters
    ----------

    master_problem : MasterProblem
        An instance of :class:`MasterProblem` representing the master problem.
    sub_problem : SubProblems
        An instance of :class:`SubProblems` representing the collection of subproblems.
    complicating_vars : list[str]
        A list of names of the binary complicating variables in the master problem.
    params : BendersParams, optional
        An instance of :class:`BendersParams` containing parameters for the Benders decomposition process.
        If not provided, default parameters will be used.

    Example
    ----------

    .. code-block:: python

        from benderslib import IntegerLShaped, MasterProblem, SubProblems, Gurobi

        # Define master and subproblem models
        master_model = ...  # Define your master problem model here
        sub_models = [...]  # Define your list of subproblem models here
        probs = [1/len(sub_models)] * len(sub_models)  # Define probabilities for each scenario

        # Initialize master and subproblems
        mp = MasterProblem(Gurobi(master_model))
        sp = SubProblems([Gurobi(sm) for sm in sub_models], probs=probs)

        # Define complicating variables (must be binary)
        complicating_vars = ['x1', 'x2', 'x3']

        # Initialize and solve
        BD = IntegerLShaped(mp, sp, complicating_vars)
        BD.solve()
    """

    def __init__(
            self,
            master_problem: MasterProblem,
            sub_problem: SubProblems,
            complicating_vars: list[str],
            optimality_cut=IntegerLShapedOCGen,
            feasibility_cut=IntegerLShapedFCGen,
            params: BendersParams = BendersParams()
    ):
        super().__init__(
            master_problem,
            sub_problem,
            complicating_vars,
            optimality_cut,
            feasibility_cut,
            params
        )

    @classmethod
    def from_models(
            cls,
            master_model,
            master_solver,
            sub_model,
            sub_solver,
            complicating_vars,
            optimality_cut=IntegerLShapedOCGen,
            feasibility_cut=IntegerLShapedFCGen,
            prob=None,
            params: BendersParams = BendersParams()
    ):
        return super().from_models(
            master_model,
            master_solver,
            sub_model,
            sub_solver,
            complicating_vars,
            optimality_cut,
            feasibility_cut,
            prob,
            params
        )


class LogicBasedBenders(BendersSolver):
    """An implementation of :doc:`../tutorials/lbbd`.

    The Logic-based Benders Decomposition is highly customizable.
    When using non-standard solvers that are not natively supported by BendersLib (typically heuristics or exact algorithms),
    users need to define their own subproblem, inheriting from :class:`LogicBasedSubProblem`.
    Users also need to implement their own optimality/feasibility cut generator, inheriting from :class:`CutGenerator`.

    Parameters
    ----------
    master_problem : MasterProblem
        An instance of :class:`MasterProblem` representing the master problem.
    sub_problem : LogicBasedSubProblem | SubProblem | Callable | SubProblems
        An instance of :class:`LogicBasedSubProblem` representing the subproblem.
        Alternatively, users can provide a function that takes the values of complicating variables as input
        and returns the optimal objective value and cut information.
    complicating_vars : list[str]
        A list of names of the complicating variables.
    optimality_cut : Type[CutGenerator] | Callable | None, optional
        A class inheriting from :class:`CutGenerator` (or a function) to generate optimality cuts.
        If not provided, no optimality cut will be added.
    feasibility_cut : Type[CutGenerator] | Callable | None, optional
        A class inheriting from :class:`CutGenerator` (or a function) to generate feasibility cuts.
        If not provided, no feasibility cut will be added.
    params : BendersParams, optional
        An instance of :class:`BendersParams` containing parameters for the Benders decomposition process.
        If not provided, default parameters will be used.

    Example
    ----------

    .. code-block:: python

        from benderslib import LogicBasedBenders, MasterProblem, LogicBasedSubProblem, Gurobi, CutGenerator

        # Define master problem model
        master_model = ...  # Define your master problem model here
        mp = MasterProblem(Gurobi(master_model))

        # Define a custom logic-based subproblem
        class MyLogicBasedSubProblem(LogicBasedSubProblem):
            def solve():
                # Implement the logic to solve the subproblem given the complicating variable values
                self.status = ...
                self.obj = ...
                self.var_values = ...

        sp = MyLogicBasedSubProblem()

        # Define a custom optimality cut generator
        class MyOptimalityCutGenerator(CutGenerator):
            def generate_cut(self, master_solution, subproblem):
                cuts = []
                # Implement the logic to generate an optimality cut
                cut = ...
                cuts.append(cut)
                return cuts

        # Define complicating variables
        complicating_vars = ['x1', 'x2', 'x3']

        # Initialize and solve
        BD = LogicBasedBenders(mp, sp, complicating_vars, optimality_cut=MyOptimalityCutGenerator)
        BD.solve()
    """

    def __init__(
            self,
            master_problem: MasterProblem,
            sub_problem: LogicBasedSubProblem | SubProblem | Callable | SubProblems,
            complicating_vars: list[str],
            optimality_cut: Type[CutGenerator] | Callable | None = None,
            feasibility_cut: Type[CutGenerator] | Callable | None = None,
            params: BendersParams = BendersParams()
    ):
        if inspect.isfunction(sub_problem):
            sub_problem = _FuncWrapperSub(complicating_vars, sub_problem)

        super().__init__(
            master_problem,
            sub_problem,
            complicating_vars,
            optimality_cut,
            feasibility_cut,
            params
        )


class GeneralizedBenders(BendersSolver):
    """An implementation of :doc:`../tutorials/gbd`.

    It builds a Benders decomposition framework using the provided master problem,
    subproblem, and complicating variables.
    The optimality cut is defined by :class:`GeneralizedOC` and generated by :class:`GeneralizedOCGen`;
    the feasibility cut is defined by :class:`GeneralizedFC` and generated by :class:`GeneralizedFCGen`.

    .. caution::
        - The class :class:`GeneralizedBenders` requires the original problem to be **linearly separable**
          into master and subproblem components, and the constraints (and objective) of the master problem are **linear**.
          The subproblem can be nonlinear, but must be **convex** (thus integer variables are not allowed).
        - There are also limitations from :doc:`solver backends <../manual/solver>`
          regarding the types of convex problems that can be handled.

    Parameters
    ----------

    master_problem : MasterProblem
        An instance of :class:`MasterProblem` representing the master problem.
    sub_problem : SubProblem
        An instance of :class:`SubProblem` representing the subproblem.
    complicating_vars : list[str]
        A list of names of the complicating variables.
    params : BendersParams, optional
        An instance of :class:`BendersParams` containing parameters for the Benders decomposition process.
        If not provided, default parameters will be used.

    Example
    ----------

    .. code-block:: python

        from benderslib import GeneralizedBenders, MasterProblem, SubProblem, Gurobi

        # Define master and subproblem models
        master_model = ...  # Define your linear master problem model here
        sub_model = ...     # Define your convex nonlinear subproblem model here

        # Initialize master and subproblem
        mp = MasterProblem(Gurobi(master_model))
        sp = SubProblem(Gurobi(sub_model))

        # Define complicating variables
        complicating_vars = ['x1', 'x2', 'x3']

        # Initialize and solve
        BD = GeneralizedBenders(mp, sp, complicating_vars)
        BD.solve()
    """

    def __init__(
            self,
            master_problem: MasterProblem,
            sub_problem: SubProblem,
            complicating_vars: list[str],
            optimality_cut=GeneralizedOCGen,
            feasibility_cut=GeneralizedFCGen
    ):
        super().__init__(
            master_problem,
            sub_problem,
            complicating_vars,
            optimality_cut,
            feasibility_cut
        )

    @classmethod
    def from_models(
            cls,
            master_model,
            master_solver,
            sub_model,
            sub_solver,
            complicating_vars,
            optimality_cut=GeneralizedOCGen,
            feasibility_cut=GeneralizedFCGen,
            prob=None,
            params: BendersParams = BendersParams()
    ):
        return super().from_models(
            master_model,
            master_solver,
            sub_model,
            sub_solver,
            complicating_vars,
            optimality_cut,
            feasibility_cut,
            prob
        )


if __name__ == '__main__':
    pass
