# coding:utf-8

from .core import BendersParams, MasterProblem, SubProblem, SubProblems, BendersSolver
from .cut import ClassicalOCGen, ClassicalFCGen, CombinatorialFCGen, CombinatorialOCGen, LShapedOCGen, LShapedFCGen, \
    IntegerLShapedOCGen, IntegerLShapedFCGen


class ClassicalBenders(BendersSolver):
    """
    A built-in implementation of the classical Benders decomposition method.
    It builds a Benders decomposition framework using the provided master problem,
    subproblem, and complicating variables.
    The optimality cut is defined by :class:`ClassicalOC` and generated by :class:`ClassicalOCGen`;
    the feasibility cut is defined by :class:`ClassicalFC` and generated by :class:`ClassicalFCGen`.

    .. caution::
        The class :class:`ClassicalBenders` requires the **subproblem be pure LP**.

    Parameters
    ----------
    master_problem : MasterProblem
        An instance of :class:`MasterProblem` representing the master problem.
    sub_problem : SubProblem
        An instance of :class:`SubProblem` representing the subproblem.
    complicating_vars : list[str]
        A list of names of the complicating variables in the master problem.
    params : BendersParams, optional
        An instance of :class:`BendersParams` containing parameters for the Benders decomposition process.
        If not provided, default parameters will be used.
    """

    def __init__(
            self,
            master_problem: MasterProblem,
            sub_problem: SubProblem,
            complicating_vars: list[str],
            optimality_cut=ClassicalOCGen,
            feasibility_cut=ClassicalFCGen,
            params: BendersParams = BendersParams()
    ):
        super().__init__(
            master_problem,
            sub_problem,
            complicating_vars,
            optimality_cut,
            feasibility_cut,
            params
        )

    @classmethod
    def from_models(
            cls,
            master_model,
            master_solver,
            sub_model,
            sub_solver,
            complicating_vars,
            optimality_cut=ClassicalOCGen,
            feasibility_cut=ClassicalFCGen,
            prob=None,
            params: BendersParams = BendersParams()
    ):
        return super().from_models(
            master_model,
            master_solver,
            sub_model,
            sub_solver,
            complicating_vars,
            optimality_cut,
            feasibility_cut,
            prob,
            params
        )


class CombinatorialBenders(BendersSolver):
    """
    A built-in implementation of the Combinatorial Benders Decomposition method.
    It builds a Benders decomposition framework using the provided master problem,
    subproblem, and complicating variables.
    The optimality cut is defined by :class:`CombinatorialOC` and generated by :class:`CombinatorialOCGen`;
    the feasibility cut is defined by :class:`NoGoodFC` and generated by :class:`CombinatorialFCGen`.

    .. caution::
        The class :class:`CombinatorialBenders` requires the **complicating variables be pure binary (0-1)**.

    Parameters
    ----------
    master_problem : MasterProblem
        An instance of :class:`MasterProblem` representing the master problem.
    sub_problem : SubProblem
        An instance of :class:`SubProblem` representing the subproblem.
    complicating_vars : list[str]
        A list of names of the complicating variables in the master problem.
    params : BendersParams, optional
        An instance of :class:`BendersParams` containing parameters for the Benders decomposition process.
        If not provided, default parameters will be used.
    """

    def __init__(
            self,
            master_problem: MasterProblem,
            sub_problem: SubProblem,
            complicating_vars: list[str],
            optimality_cut=CombinatorialOCGen,
            feasibility_cut=CombinatorialFCGen,
            params: BendersParams = BendersParams()
    ):
        super().__init__(
            master_problem,
            sub_problem,
            complicating_vars,
            optimality_cut,
            feasibility_cut,
            params
        )

    @classmethod
    def from_models(
            cls,
            master_model,
            master_solver,
            sub_model,
            sub_solver,
            complicating_vars,
            optimality_cut=CombinatorialOCGen,
            feasibility_cut=CombinatorialFCGen,
            prob=None,
            params: BendersParams = BendersParams()
    ):
        return super().from_models(
            master_model,
            master_solver,
            sub_model,
            sub_solver,
            complicating_vars,
            optimality_cut,
            feasibility_cut,
            prob,
            params
        )


class LShaped(BendersSolver):
    """
    A built-in implementation of the L-shaped method for two-stage stochastic programming.
    It builds a Benders decomposition framework using the provided master problem,
    subproblem, and complicating variables.
    The optimality cut is defined by :class:`LShapedOC` (single-cut) or :class:`ClassicalOC` (multi-cut),
    and generated by :class:`LShapedOCGen`;
    the feasibility cut is defined by :class:`ClassicalFC` and generated by :class:`LShapedFCGen`.

    .. caution::
        The class :class:`LShaped` requires the (second-stage) **subproblems be pure LP**.

    Parameters
    ----------
    master_problem : MasterProblem
        An instance of :class:`MasterProblem` representing the master problem.
    sub_problem : SubProblems
        An instance of :class:`SubProblems` representing the collection of subproblems.
    complicating_vars : list[str]
        A list of names of the complicating variables in the master problem.
    params : BendersParams, optional
        An instance of :class:`BendersParams` containing parameters for the Benders decomposition process.
        If not provided, default parameters will be used.
    """

    def __init__(
            self,
            master_problem: MasterProblem,
            sub_problem: SubProblems,
            complicating_vars: list[str],
            optimality_cut=LShapedOCGen,
            feasibility_cut=LShapedFCGen,
            params: BendersParams = BendersParams()
    ):
        super().__init__(
            master_problem,
            sub_problem,
            complicating_vars,
            optimality_cut,
            feasibility_cut,
            params
        )

    @classmethod
    def from_models(
            cls,
            master_model,
            master_solver,
            sub_model,
            sub_solver,
            complicating_vars,
            optimality_cut=LShapedOCGen,
            feasibility_cut=LShapedFCGen,
            prob=None,
            params: BendersParams = BendersParams()
    ):
        return super().from_models(
            master_model,
            master_solver,
            sub_model,
            sub_solver,
            complicating_vars,
            optimality_cut,
            feasibility_cut,
            prob,
            params
        )


class IntegerLShaped(BendersSolver):
    """
    A built-in implementation of the Integer L-shaped method for two-stage stochastic programming with
    binary complicating variables and integer recourse.
    It builds a Benders decomposition framework using the provided master problem,
    subproblem, and complicating variables.
    The optimality cut is defined by :class:`CombinatorialOC` and generated by :class:`IntegerLShapedOCGen`;
    the feasibility cut is defined by :class:`NoGoodFC` and generated by :class:`IntegerLShapedFCGen`.

    .. caution::
        The class :class:`IntegerLShaped` requires the complicating variables to be **pure binary (0-1)**,
        integer variables in the subproblems are allowed.

    Parameters
    ----------
    master_problem : MasterProblem
        An instance of :class:`MasterProblem` representing the master problem.
    sub_problem : SubProblems
        An instance of :class:`SubProblems` representing the collection of subproblems.
    complicating_vars : list[str]
        A list of names of the binary complicating variables in the master problem.
    params : BendersParams, optional
        An instance of :class:`BendersParams` containing parameters for the Benders decomposition process.
        If not provided, default parameters will be used.
    """

    def __init__(
            self,
            master_problem: MasterProblem,
            sub_problem: SubProblems,
            complicating_vars: list[str],
            optimality_cut=IntegerLShapedOCGen,
            feasibility_cut=IntegerLShapedFCGen,
            params: BendersParams = BendersParams()
    ):
        super().__init__(
            master_problem,
            sub_problem,
            complicating_vars,
            optimality_cut,
            feasibility_cut,
            params
        )

    @classmethod
    def from_models(
            cls,
            master_model,
            master_solver,
            sub_model,
            sub_solver,
            complicating_vars,
            optimality_cut=IntegerLShapedOCGen,
            feasibility_cut=IntegerLShapedFCGen,
            prob=None,
            params: BendersParams = BendersParams()
    ):
        return super().from_models(
            master_model,
            master_solver,
            sub_model,
            sub_solver,
            complicating_vars,
            optimality_cut,
            feasibility_cut,
            prob,
            params
        )


class LogicBasedBenders(BendersSolver):
    pass


class GeneralizedBenders(BendersSolver):
    pass


class BendersDual(BendersSolver):
    pass


if __name__ == '__main__':
    pass
