PYOMO_SOLVER_OPTIONS:
  gurobi:
    'OutputFlag': 0
    'LogToConsole': 0
    'InfUnbdInfo': 1
    'QCPDual': 1
  gurobi_direct:
    'OutputFlag': 0
    'LogToConsole': 0
    'InfUnbdInfo': 1
    'QCPDual': 1
  scip:
    'presolving/maxrounds': 0
    'separating/maxrounds': 0
    'propagating/maxrounds': 0
    'lp/alwaysgetduals': True
